### ISSUE TITLE
All data names have "all-underscore" aliases

### ISSUE THREAD

**Issue by nautolycus** [COMCIFS/cif_ed#2]
Although there is a general desire to move away from all-underscore data names, especially in new dictionaries, all the names in this draft dictionary have been supplied with all-underscore aliases. The justification is that we expect initial uptake will be to files generated by existing software that already uses all-underscore core data names.

**Comment by jamesrhester** [comment]
I don't think that justification holds water. Where something has been added to an enumerated list, the dot-style data name will be aliased to the all-underscore style data name anyway. Where a data name is new, software will need to be (re)written to handle it anyway, and unmodified old software will ignore new data names. So I'd be in favour of using new-style data names, and if complaints arise that software has already, at this early stage, been written with all underscore data names, we can add an alias.

**Comment by nautolycus** [comment]
OK, I've removed the new aliases from this iteration (and also updated the recommendations.md file to - mostly - avoid use of all-underscore names). I'll mark this issue as resolved, but be prepared for comeback from the community.
